<?php
/**
 * @file
 * content_types_news.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function content_types_news_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function content_types_news_node_info() {
  $items = array(
    'news' => array(
      'name' => t('News'),
      'base' => 'node_content',
      'description' => t('Publish news articles that explain how UNDP engages with governments and other partners to achieve positive climate change and adaptation policy outcomes.'),
      'has_title' => '1',
      'title_label' => t('Headline'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
